#!/bin/bash

# Copyright (C) 2024  KA Wright

# This small script changes the environment variables used in my personal
# .vimrc file for color themes to a dark-on-light scheme.

export VIM_FG=16
export VIM_BG=231

echo "VIM color scheme changed to LIGHT"
